# AULA 2 DEMONSTRAÇÃO- Multi-Layer Perceptron

Aula 2- Aula Assíncrona

---

## Perceptrons e Multi-layer Perceptrons

- Implementando um modelo de perceptron com Pytorch

---

In [84]:
import torch

### Modelo Linear

* construir um modelo linear com classes orientadas a objeto
    * modelo linear: w.X + b

In [85]:
class Model():
    # construtor inicializa os parametros
    def __init__(self, num_inputs):
        # w inicial: amostrando de uma distribuicao normal media 0 e desvio padrao 1
        self.w = torch.normal(0, 1, (num_inputs, 1))
        # b inicial: valor constante 1 ou 0, as vezes com 1/total de classes
        self.b = torch.zeros(1)

    # forward: de x até a saida
    def forward(self, X):
        # X w + b
        return X @ self.w + self.b # multipliação e soma matricial

    # funcao custo
    def loss(self, y, y_hat):
        yreshape = y.reshape(y_hat.shape)
        l = (y_hat - yreshape)**2/2
        return l.mean()

In [86]:
model = Model(2)
model.w, model.forward(torch.tensor([[1,1]], dtype = torch.float32))

(tensor([[-1.2659],
         [ 0.4702]]),
 tensor([[-0.7956]]))

### Modelo em Prática

- testar o modelo com um problema de regressão 
    - dois datasets: x e y
        - x tem um ruído 

In [87]:
x = torch.arange(16,  dtype = torch.float32).reshape((8,2)) + torch.normal(0,0.5, (8,2))
y =  torch.arange(8,  dtype = torch.float32)
x, y

(tensor([[ 0.3648,  1.2200],
         [ 1.5084,  2.8066],
         [ 3.6140,  5.1815],
         [ 6.1235,  5.9222],
         [ 7.9385,  9.6703],
         [ 9.4239, 10.9706],
         [11.2241, 13.9327],
         [13.6394, 14.5576]]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7.]))

In [88]:
y_hat = model.forward(x)
y_hat, y

(tensor([[  0.1119],
         [ -0.5897],
         [ -2.1384],
         [ -4.9667],
         [ -5.5019],
         [ -6.7707],
         [ -7.6566],
         [-10.4202]]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7.]))

In [89]:
# quão bom ta esse modelo acima?
model.loss(y, y_hat)

tensor(50.1212)

valor acima é a perda quadrática média pra ess modelo, ou seja, quanto menor essa perda melhor

### Modelo com gradiente

- para garantir que haja uma evolução, vamos usar o gradient descent

In [90]:
class Model2():
    # construtor inicializa os parametros
    def __init__(self, num_inputs):
        # w inicial: amostrando de uma distribuicao normal media 0 e desvio padrao 1
        self.w = torch.normal(0, 1, (num_inputs, 1), requires_grad=True)
        # b inicial: valor constante 1 ou 0, as vezes com 1/total de classes
        self.b = torch.zeros(1, requires_grad=True)

    # forward: de x até a saida
    def forward(self, X):
        # X w + b
        return X @ self.w + self.b # multipliação e soma matricial

    # funcao custo
    def loss(self, y, y_hat):
        yreshape = y.reshape(y_hat.shape)
        l = (y_hat - yreshape)**2/2
        return l.mean()

In [91]:
model2 = Model2(2)

y_hat = model2.forward(x)
y_hat, model2.loss(y, y_hat)

(tensor([[ 2.0002],
         [ 5.2100],
         [10.3726],
         [13.6680],
         [20.4443],
         [23.5735],
         [29.2613],
         [32.3127]], grad_fn=<AddBackward0>),
 tensor(125.1773, grad_fn=<MeanBackward0>))

* por enquanto não vamos usar, mas com esse grad_fn ativado, já poderíamos implementar o gradient descent

*obs: esse model é quasee um Perceptron, falta alguns ajustes para ser um propriamente dito (tipo uma função de ativação)*

---