# AULA 1 DEMONSTRAÇÃO- INTRODUÇÃO

SCC0270- 17/08

---

## Introdução ao PYTORCH e NUMPY

---

### Numpy



In [91]:
import numpy as np

np.arange(5)

array([0, 1, 2, 3, 4])

In [92]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.zeros((3,5)) # matriz

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [94]:
np.ones((1,10))*5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

---

### **PyTorch**

Tensoes: Generalização de vetores...\
1 dimensão   -> vetor \
2 dimensões  -> matriz \
3+ dimensões -> tensor 

In [95]:
import torch

torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

*obs: note que um tensor é diferente de um array no output*

In [96]:
A = torch.ones((2,5))

# Dimensões d eum tensor (não precisa ta no print)
A.shape, print(f'dimensões: {A.shape[0]} e {A.shape[1]}')

dimensões: 2 e 5


(torch.Size([2, 5]), None)

In [97]:
# não altera o A diretamente (não é in-place)
B = A.reshape((5,2))
B

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

*obs: linha * coluna deve continuar igual*

**OPERAÇÕES**

INDEXAÇÃO e FATIAMENTO

In [98]:
A[0], A[0:4], (A[:-2])

(tensor([1., 1., 1., 1., 1.]),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([], size=(0, 5)))

**Tipagem**

In [99]:
A.dtype

torch.float32

In [100]:
C = torch.arange(1,11, dtype=int)
C.dtype

torch.int64

**Operações Elemento a Elemento**

In [101]:
# unários
torch.log(C) # log um a um

tensor([0.0000, 0.6931, 1.0986, 1.3863, 1.6094, 1.7918, 1.9459, 2.0794, 2.1972,
        2.3026])

In [102]:
# binários
D = torch.ones(C.shape)*1.5

C + D, C * D, C ** D # soma, multiplicação e exponenciação

(tensor([ 2.5000,  3.5000,  4.5000,  5.5000,  6.5000,  7.5000,  8.5000,  9.5000,
         10.5000, 11.5000]),
 tensor([ 1.5000,  3.0000,  4.5000,  6.0000,  7.5000,  9.0000, 10.5000, 12.0000,
         13.5000, 15.0000]),
 tensor([ 1.0000,  2.8284,  5.1962,  8.0000, 11.1803, 14.6969, 18.5203, 22.6274,
         27.0000, 31.6228]))

**Operações Lógicas**

In [103]:
C > D

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])

In [104]:
C[C > D]

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

construir tensores:

In [105]:
mascara = torch.tensor([True]*2 + [False]*4 + [True]*4)

mascara, C[mascara]

(tensor([ True,  True, False, False, False, False,  True,  True,  True,  True]),
 tensor([ 1,  2,  7,  8,  9, 10]))

**Broadcasting**
\
Operações em tensores de formados diferentes, expnadindo as dimensões deles

In [106]:
x = torch.arange(4).reshape(4,1)
y = torch.arange(2).reshape(1,2)
x, y

(tensor([[0],
         [1],
         [2],
         [3]]),
 tensor([[0, 1]]))

In [107]:
# broadcasting expandiu as dimensões da matriz x ao longo das colunas
# e de y ao longo das linhas antes da soma
x + y

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

**Cópia de tensores**
- cópia rasa
- cópia profunda

In [108]:
# obs: C e D tem mesmo size
C = torch.arange(1,11)

id_antes = id(C) 

C = C + D

id(C) == id_antes

False

resultado: False! ou seja, ele não está reutilizando a memória, para isso, devemos fazer:

In [109]:
C = torch.arange(1,11)

id_antes = id(C) 

C[:] = C + D #!<--

id(C) == id_antes

True

Cópia com o torch (rasa ou profunda):

In [110]:
# CÓPIA RASA
id_antes = id(C)
D = C # D é uma view de C
id(D) == id_antes

True

In [111]:
# CÓPIA PROFUNDA
id_antes = id(C)
D = C.clone() # Clona C e cria a variável D
id(D) == id_antes

False

**Vetores e Matrizes**

In [112]:
x = torch.arange(5, dtype=torch.float32)
y = torch.arange(25).reshape(5,5)
x, y

(tensor([0., 1., 2., 3., 4.]),
 tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]]))

In [113]:
# Trannspor matriz/vetor
A.T, x.T

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([0., 1., 2., 3., 4.]))

**Redução** \
Calcular ao longo de dimensões do tensor

In [114]:
# redução de A para A.sum() e etc
A ,A.sum(), A.sum(axis=0), A.mean()

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor(10.),
 tensor([2., 2., 2., 2., 2.]),
 tensor(1.))

**Produto Interno** \
x^T y = sum i (xi yi)

In [115]:
a = torch.arange(1,6, dtype=torch.float32)
b = torch.ones(5) * 3
a, b

(tensor([1., 2., 3., 4., 5.]), tensor([3., 3., 3., 3., 3.]))

In [116]:
torch.dot(a, b)

tensor(45.)

In [117]:
# multiplicação matriz - vetor
A, x, torch.mv(A, x)

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([0., 1., 2., 3., 4.]),
 tensor([10., 10.]))

In [118]:
# multiplicação matriz - matriz
torch.mm(A,A.T)

tensor([[5., 5.],
        [5., 5.]])

podemos usar *atalhos*

In [119]:
A@A.T

tensor([[5., 5.],
        [5., 5.]])

**Norma de Tensor** \
Norma Euclidiana (L2): raiz quadrada da soma dos quadrados

In [120]:
torch.norm(x)

tensor(5.4772)