# AULA 4 DEMONSTRAÇÃO 2- Redes Convolucionais


Aula 4- Aula Assíncrona
https://www.youtube.com/watch?v=yvsJDLn6Ots&ab_channel=MoacirAntonelliPonti

---

## PyTorch Custom Dataset

- customização de dataset

---

In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

Para definir um dataset personalizado, para qualquer tipo de dados, projetamos uma classe herdando de `Dataset` e contendo os métodos:
- `__init__` que vai atribuir os dados
- `__len__` que retorna o tamanho do dataset
- `__getitem__` que retorna um item baseado em um índice

In [23]:
class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data
        
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        return self.data[idx]

* essa classe será usada para armazenar os dados (exemplo abaixo)

In [24]:
random_data = np.random.randint(0, 20, (20)) # valores aleatórios 
print('Dados: ', random_data)

dataset = MyDataset(random_data) # valores acima na classe
print('Total de exemplos no dataset: ', len(dataset))
print('Podemos usar colchetes pois implementamos o __getitem__, exemplo:', dataset[2])
print(dataset[0:5])

Dados:  [ 7 14  7  0 14  9 15  7  1  4 15 14  6 18  1 16  8  6 11 11]
Total de exemplos no dataset:  20
Podemos usar colchetes pois implementamos o __getitem__, exemplo: 7
[ 7 14  7  0 14]


In [25]:
# usando dataloader da aula passada
train_dataloader = DataLoader(dataset, batch_size=6, shuffle=False) # como shuffle ta False, ele pega os 1ºs 6 itens
next_batch = next(iter(train_dataloader))
print(next_batch)

tensor([ 7, 14,  7,  0, 14,  9], dtype=torch.int32)


In [26]:
iterator_train = iter(train_dataloader)
next_batch = next(iterator_train)
print(next_batch) # 6 primeiros elementos
next_batch = next(iterator_train)
print(next_batch) # segunda leva de 6 elementos
next_batch = next(iterator_train)
print(next_batch) # terceira leva de 6 elementos
next_batch = next(iterator_train)
print(next_batch) # ultima leva com os que sobraram
## next_batch = next(iterator_train)
## print(next_batch) # gera erro pois nao há mais items para retornar

tensor([ 7, 14,  7,  0, 14,  9], dtype=torch.int32)
tensor([15,  7,  1,  4, 15, 14], dtype=torch.int32)
tensor([ 6, 18,  1, 16,  8,  6], dtype=torch.int32)
tensor([11, 11], dtype=torch.int32)


In [27]:
# outro dataset contendo 10 instancias com 4 features cada
random_data2 = np.random.randint(1,5, (10, 4))
print('Dados: ', random_data2)

dataset2 = MyDataset(random_data2)
print('Total de exemplos no dataset: ', len(dataset2))
print('Podemos usar colchetes pois implementamos o __getitem__, exemplo:', dataset2[2])
print(dataset2[:3])

Dados:  [[3 4 1 2]
 [4 1 3 2]
 [1 3 2 2]
 [2 2 2 1]
 [2 3 3 4]
 [3 4 2 3]
 [1 2 3 4]
 [3 2 3 1]
 [3 3 2 3]
 [1 3 1 4]]
Total de exemplos no dataset:  10
Podemos usar colchetes pois implementamos o __getitem__, exemplo: [1 3 2 2]
[[3 4 1 2]
 [4 1 3 2]
 [1 3 2 2]]


In [28]:
# dataloader 2
train_dataloader2 = DataLoader(dataset2, batch_size=3, shuffle=True) # shuffle on, valores aleatrios
iterator_train = iter(train_dataloader2)

In [29]:
next_batch = next(iterator_train, None)
while next_batch != None: # iterar pelos batchs
    print(next_batch) # vale lembrar que o shuffle ta True, então os valores sao aleatorios no dataset
    next_batch = next(iterator_train, None)

tensor([[1, 2, 3, 4],
        [3, 4, 2, 3],
        [3, 3, 2, 3]], dtype=torch.int32)
tensor([[1, 3, 1, 4],
        [3, 4, 1, 2],
        [2, 3, 3, 4]], dtype=torch.int32)
tensor([[4, 1, 3, 2],
        [2, 2, 2, 1],
        [1, 3, 2, 2]], dtype=torch.int32)
tensor([[3, 2, 3, 1]], dtype=torch.int32)


---
### Um dataset mais completo

* Agora com rótulos e usando pandas DataFrame

In [30]:
dataframe_breast_cancer = pd.read_csv('data.csv')
cols_dataframe = list(dataframe_breast_cancer)
print(dataframe_breast_cancer.columns)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

* **prof não disponibilizou o dataset, ver no github dele o modulo4 com os resultados já prontos**
    * https://github.com/maponti/rnap_curso/tree/eaa12afef3b7e2f2ee31e1d31c07d64cc7f59f53